### ISSUE TITLE
block texture rendering (Immersive Engineering)

### ISSUE THREAD

**Issue by jennybrush** [Migmag789/Beyond-The-Minecraft#1]
BTM v1.6.0 - Unable to render scaffolding texture for IE steel scaffolding blocks when placed. Texture visibility okay in JEI and player inventory. (tested both with OptiFine_1.12_HD_U_C5 and without)

**Comment by Migmag789** [comment]
Yes, I know, this is the same bug with All the Mods 3. Test the 1.7.0-build002, and if that's don't work, I'm going to report the bug to the IE author ;)

**Comment by Migmag789** [comment]
Now I know what's the problem. That's FoamFix ;)
That are going to be fixed when the 0.8.0 of FoamFix is released ;)
