### ISSUE TITLE
Stuck and glitch when using Portal to/from Nether

### ISSUE THREAD

**Issue by gelonsoft** [Migmag789/Beyond-The-Minecraft#11]
When teleporting to Nether/Overworld using Portal occurs glitch/stuck.
During glitch/stuck can't jump, crash blocks or interact with nearby blocks - only throw items from inventory.
Logs and video of glitch attached.

Thanks in advance for fast response and resolution of bug!
[logs.zip](https://github.com/Migmag789/Beyond-The-Minecraft/files/1399384/logs.zip)

[2017-10-19 20-13-45.zip](https://github.com/Migmag789/Beyond-The-Minecraft/files/1399375/2017-10-19.20-13-45.zip)

**Comment by gelonsoft** [comment]
Version of modpack is latest (1.7.4). In previous version of madpack (1.7.3) the same issue.

**Comment by Migmag789** [comment]
Please update Universal Remote manually to the 0.9.6 ;)
