### ISSUE TITLE
Crash in EvilCraft when meet NetherFish

### ISSUE THREAD

**Issue by gelonsoft** [Migmag789/Beyond-The-Minecraft#12]
Occured crash in EvilCraft. Manual updating to latest version of Evil Craft doesn't help. 
Created issue ub Evil Craft git: https://github.com/CyclopsMC/EvilCraft/issues/599

**Comment by Migmag789** [comment]
Thank you ^^

**Comment by gelonsoft** [comment]
@Migmag789 the game keeps crashing with the same NullPointer exception when ticking entities - and not only for entities from EvilCraft mod (so, EvilCraft mod is not the root cause of issue). But when I updated Universal Remote mod, the issue resolved. So, please update Universal Remote to latest version (I uses 0.9.9) to make game for other players of this awesome modpack more stable.
Thanks in advance!

**Comment by Migmag789** [comment]
Ok, thank you ! :D
