### ISSUE TITLE
crash with 2.0 - 004

### ISSUE THREAD

**Issue by jlewismoss** [Migmag789/Beyond-The-Minecraft#13]
Have had two crashes.  Both were right after an encounter with a skeleton wearing a head (steve head and wither skeleton skull).  World becomes unplayable because when I start back up the skeleton is still there and another crash.

Used lost city (bop) generation type for world.
[crash-2017-10-28_13.23.01-server.txt](https://github.com/Migmag789/Beyond-The-Minecraft/files/1424453/crash-2017-10-28_13.23.01-server.txt)

**Comment by jlewismoss** [comment]
Oh.  Should mention.  This is on a linux system using multimc to create the instance and curseDownloader to download the mods and combining the two.

**Comment by Migmag789** [comment]
I'm going to fix it ;)

**Comment by Migmag789** [comment]
thanks for report :D

**Comment by jlewismoss** [comment]
Looks like I got a similar crash with 005.  Want the crash report?

**Comment by Migmag789** [comment]
Seriously o.O

**Comment by Migmag789** [comment]
Give me the crash report, please.
