### ISSUE TITLE
Crash with zombie in 005

### ISSUE THREAD

**Issue by jlewismoss** [Migmag789/Beyond-The-Minecraft#14]
[crash-2017-10-28_15.03.47-server.txt](https://github.com/Migmag789/Beyond-The-Minecraft/files/1424542/crash-2017-10-28_15.03.47-server.txt)

**Comment by jlewismoss** [comment]
I made sure to make a completely clean install of this and it still occurred.

**Comment by Migmag789** [comment]
With the 2.0 too ? Do you have added any mods ?

**Comment by jlewismoss** [comment]
I'm getting a different crash with 2.0.  Somethnig in ftbutilties.

[crash-2017-10-29_19.29.04-client.txt](https://github.com/Migmag789/Beyond-The-Minecraft/files/1425592/crash-2017-10-29_19.29.04-client.txt)

**Comment by jlewismoss** [comment]
No added mods.  Sorry forgot to answer this question.

**Comment by Migmag789** [comment]
Yes I know this crash, I'm going to try to fix it ;)

**Comment by LucyDemooon** [comment]
The Fix is Update the FTBLib to 4.2.3 !

**Comment by Migmag789** [comment]
Yes, the bug is fixed in 2.0.1
