### ISSUE TITLE
cant join server

### ISSUE THREAD

**Issue by LucyDemooon** [Migmag789/Beyond-The-Minecraft#15]
Hey,
Cant join the server with the 2.0 version of the modpack always when i login to te server i got automatic an connection lost sometimes an crash. 

[crash-2017-11-04_04.57.14-client.txt](https://github.com/Migmag789/Beyond-The-Minecraft/files/1442950/crash-2017-11-04_04.57.14-client.txt)
[crash-2017-11-04_05.14.35-client.txt](https://github.com/Migmag789/Beyond-The-Minecraft/files/1442951/crash-2017-11-04_05.14.35-client.txt)

**Comment by Migmag789** [comment]
Update FTB Utilities and don't update Forge

**Comment by LucyDemooon** [comment]
FTBUtilities 4.2.2 
FTBLib 4.2.3
are on server and client don't change anything

**Comment by Migmag789** [comment]
Really ? o.O

**Comment by LucyDemooon** [comment]
yes really.

**Comment by Migmag789** [comment]
So disable FTB Utilities or use 2.0.2
