### ISSUE TITLE
Server version 1.7.0 build003 Crash: Extra Utilities 2 exception

### ISSUE THREAD

**Issue by FelixShift** [Migmag789/Beyond-The-Minecraft#2]
I know this is already been discussed on the discord, but it still took me a while to find it so I wanted to make the issue a bit more public for others. In version 1.7.0 build003 when launching a server, the server will crash with the following error. The author reported they are working on a fix.

https://pastebin.com/uQQninME

**Comment by Migmag789** [comment]
Yes, I know, that's fixed on the 1.7.0 beta, I'm going to release this version in few hours ;)
