### ISSUE TITLE
Server version 1.7.0-prerelease Crash: Missing Mods - modelloader

### ISSUE THREAD

**Issue by FelixShift** [Migmag789/Beyond-The-Minecraft#3]
Server is crashing due to a missing mod that is included with the new install of the pack. I noticed a "," at the end of the mod name in the crash. Maybe this is the reason?

https://pastebin.com/ftGiACkM

**Comment by Migmag789** [comment]
Install model loader 1.0.4 for Magneticraft <(^^)>

**Comment by FelixShift** [comment]
If you look in the discord I show that it was installed while receiving the error. I also did install it myself and received the same crash.

**Comment by Migmag789** [comment]
rename the mod modelloader-1.0.4,

If that don't work... I can't help you :/
