### ISSUE TITLE
Client version 1.7.0-prerelease Crash: Caught exception from Tech Reborn

### ISSUE THREAD

**Issue by FelixShift** [Migmag789/Beyond-The-Minecraft#4]
Client is crashing due to an exception from Tech Reborn.

https://pastebin.com/qT6B1yQa

**Comment by Migmag789** [comment]
Use the TwitchApp ^^ if you have this same crash again, I update the Modpack ;)

**Comment by FelixShift** [comment]
Used the twitch app and multiMC. Crash was confirmed by another in the discord.

"Fr34k_Max - Yesterday at 4:32 PM
jup, crash on startup: The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Tech Reborn (techreborn)"

**Comment by Migmag789** [comment]
Ok, I'm going to report the error to the RebornTM ;)
