### ISSUE TITLE
Crash while loading recipies

### ISSUE THREAD

**Issue by mdinnocenzo** [Migmag789/Beyond-The-Minecraft#6]
While using JEI to get recipe for blast brick, system crashed.  logging back in and trying to open crafting table now crashes game immediately.  It also appears that opening inventory will do the same thing.

have a backup file if you want to test the world.

The game crashed whilst rendering ingredient
Error: java.lang.IllegalStateException: Not building!

[crash-2017-09-28_09.44.32-client.txt](https://github.com/Migmag789/Beyond-The-Minecraft/files/1341568/crash-2017-09-28_09.44.32-client.txt)

**Comment by Migmag789** [comment]
Thank you for report ;)
I'm going to report the crash, that's a error from Random Things ;)

**Comment by mdinnocenzo** [comment]
Was able to manually update JEI and Random Things through the launcher.  Seems to have fixed it.  

jei_1.12.2-4.7.11.101.jar
RandomThings-MC1.12.2-4.0.6.1.jar

Hope this helps, just looks like they need an update.

**Comment by Migmag789** [comment]
Okay, thank you very much ^^

**Comment by Migmag789** [comment]
Oh, I have the latest version

**Comment by Migmag789** [comment]
oops, wrong issue x)
