### ISSUE TITLE
Server version 1.7.2 is not starting...

### ISSUE THREAD

**Issue by SirJayZett** [Migmag789/Beyond-The-Minecraft#7]
Hi there!

Just downloaded the server files of the version 1.7.2, but it will not start installing the server. After running the Server.bat it shows following error message:

We appear to be missing one or more essential library files.
You will need to add them to your server before FML and Forge will run successfully.java.lang.ClassNotFoundException: net.minecraft.launchwrapper.Launch
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:44)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:31)

Then it just closes the window.
Java is up-to-date (installed the newest version for 64-bit just a few minutes ago).

What is still missing here?

**Comment by Migmag789** [comment]
Java 64-bits is your best friend 4ever. :)

**Comment by SirJayZett** [comment]
Now I found out on myself, what is missing in the Server-Files:
It looks like you forgot the installer-script ^^
I took the installer from 1.6.0 and modified it, so it installs the right forge version and now the server runs.

Well, I guess maybe you should update the server-files with the necessary installer-script. :)

**Comment by Migmag789** [comment]
Oh okay ^^ If you want you can give me your server files, and with your server files I can upload it to the curse page to help users have this crash ;)

**Comment by SirJayZett** [comment]
Of course... Here is the Install-Script - Just remove the ".txt" to convert it into an .bat file. Thats all. Then it worked all to me.

[install_server.bat.txt](https://github.com/Migmag789/Beyond-The-Minecraft/files/1347499/install_server.bat.txt)

**Comment by Migmag789** [comment]
Oh okay ^^
