### ISSUE TITLE
1.7.3 issues

### ISSUE THREAD

**Issue by lallatilallaa** [Migmag789/Beyond-The-Minecraft#8]
https://pastebin.com/Vwxbbh11

This keeps happening in the 1.7.3 version and also very weird glitches every time you change a dimension, like you get stuck and take damage and all of the piping is messed up

**Comment by Migmag789** [comment]
Thank you for the report, I'm going to share the crash report to the Mekanism creator ;)

**Comment by gelonsoft** [comment]
The same issue in 1.7.4.
After manual updating UniversalRemote to UniversalRemote-1.12-0.9.6.jar issue resolved.

**Comment by Migmag789** [comment]
I'm going to fix when I update to 2.0.0 Beyond the Minecraft ;) I reported this crash to the creator in the discord ;)
