### ISSUE TITLE
Sleeping issue in 1.7.3

### ISSUE THREAD

**Issue by BruceLeeWannaBe** [Migmag789/Beyond-The-Minecraft#9]
Whenever I sleep I stand at the end of the bed and cannot move or leave the bed. This isnt an issue in single player but on a server it is impossible to leave the bed if no one else can sleep. I also cannot enter boats.

**Comment by Migmag789** [comment]
Yes, that's a big issue I have too... Restart your world ;)
I don't know why there is this horrible problem... That's just INSANE.

**Comment by BruceLeeWannaBe** [comment]
Creating a new world does not fix the problem.

**Comment by Migmag789** [comment]
Restart your world, not make a new world
Deconnect, and reconnect

**Comment by BruceLeeWannaBe** [comment]
that doesnt work either

**Comment by Migmag789** [comment]
I don't know how to fix the problem... ;(
